require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Layout:
  Enabled: false

Metrics:
  Enabled: false

Style:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true
