---
language: ruby
cache: bundler
gemfile: ci-gemfiles/ruby-3.0
script:
  - bundle exec rake default
after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - rvm: 3.0
      gemfile: ci-gemfiles/ruby-3.0
      env:
        - ENABLE_OJ=true
        - RUN_SIMPLECOV=true
        - RUN_RUBOCOP=true
        - RUN_CODECOV=true
